name       : nvidia-container-runtime
version    : 3.4.0
release    : 3
source     :
    - https://github.com/NVIDIA/nvidia-container-runtime/archive/v3.4.0.tar.gz : bc27c35717cf5c50fc17a7066e34dcd2dac2cb4165cc14b551d6ac20f15998c4
license    : Apache-2.0
component  : programming.tools
summary    : NVIDIA container runtime
description: |
    A thin wrapper around the native runc that allows users to run GPU enabled containers
builddeps  :
    - golang
rundeps    :
    - nvidia-container-toolkit
setup      : |
    %patch -p1 < $pkgfiles/support-stateless-configuration.patch
build      : |
    ln -sv vendor src/src
    %make -C src build GOPATH=$workdir/src
install    : |
    install -Dm00755 src/nvidia-container-runtime $installdir/usr/bin/nvidia-container-runtime
